### ISSUE TITLE
Restrict IAM Policy to Specific Resources

### ISSUE THREAD

**Issue by shamsher31** [platform9/emp-roadmap#1]
### Requirement:

The current EMP IAM Policy allows broad access to EC2, EKS, Auto Scaling, and S3 actions on all resources ("*"). Customers raised security concerns regarding this unrestricted access. We must revise the policy to restrict actions to specific resources where possible. 

### Acceptance Criteria:

Policy Restriction:

- Review the current EMP IAM policy and identify actions that can be restricted to specific resources.
- Modify the policy to specify resource ARNs wherever possible, such as EC2 and S3 actions.
- Update the policy to remove or restrict unnecessary permissions.

Policy Examples:

The policy should follow the structure as shown below:

Example for EC2 resources:

```
PolicyDocument:
  Statement:
    - Effect: Allow
      Action:
        - ec2:AllocateAddress
        - ec2:AssociateRouteTable
      Resource:
        - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:*'

```
Example for S3 buckets:

```
PolicyDocument:
  Statement:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - !Sub 'arn:aws:s3:::${BucketName}/*'
```
